JDP190903-3
metho/project-JDP-1909-03 pull request #1
Opened 2019-09-18 10:49 UTC by mwiski

Utworzyłem endpoint'y w klasie CartController ze zwracanymi testowymi danymi. Dodatkowo stworzyłem folder domain i w nim puste klasy Cart, CartDto, Order, OrderDto, Product, ProductDto - potrzebowałem ich do zwracania wartości w kontrolerze.

2019-09-18 20:27 UTC, mps4dev requested changes
:-1: 
moim zdaniem kosmetyczne poprawki. Co ty na to @metho ?

2019-09-18 20:27 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "products/add")
ja bym poprostu dał `calue = "product"` - metoda `PUT` doprecyzowuje.

2019-09-18 20:27 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "products/delete")
`value = "product" - tutaj `DELETE` doprecyzowuje

2019-09-18 20:27 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @RequestMapping(method = RequestMethod.POST, value = "order/new")
`value = "order"`

2019-09-18 20:27 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public OrderDto createOrderBasedOnCart(Long cartId) {
`createOrderForCart` ?

2019-09-20 06:07 UTC, metho requested changes

2019-09-20 06:07 UTC, metho commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +}
Zazwyczaj lepiej zostawiać na końcu pliku pustą linię. Tutaj github zwraca na to uwagę.
Zobacz sobie temat:
https://stackoverflow.com/questions/5813311/no-newline-at-end-of-file/44641937

2019-09-20 06:07 UTC, metho commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    static final String BASE_API = "v1/cart";
Jeśli chcesz definiować tą ściezkę w zmiennej, to warto ją oznaczyć jeszcze wtedy też jako private

2019-09-20 06:07 UTC, metho commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @RequestMapping(method = RequestMethod.POST, value = "new")
W nowych wersjach Springa wprowadzono też krótszy zapis tych mapowań. 
Np zamiast @RequestMapping(method = RequestMethod.POST) można użyć @PostMapping
Spróbuj zapisać te endpointy przy użyciu tej notacji.
Możesz poczytać o tym tutaj: https://www.baeldung.com/spring-new-requestmapping-shortcuts

2019-09-20 06:07 UTC, metho commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "products/delete")
Czemu usuwanie produktów to operacja PUT a nie DELETE?

2019-09-20 14:58 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    static final String BASE_API = "v1/cart";
musi być public, niestety, @metho @mwiski

2019-09-20 14:59 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    static final String BASE_API = "v1/cart";
Moim zdaniem jest okej.

2019-09-20 15:22 UTC, mwiski commented
Ok, dokonałem poprawek

2019-09-21 09:12 UTC, metho approved these changes

2019-09-21 09:12 UTC, metho commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    static final String BASE_API = "v1/cart";
ok

2019-09-21 11:47 UTC, merged