JDP190903-17 Encja Product-Testy
metho/project-JDP-1909-03 pull request #27
Opened 2019-09-29 21:23 UTC by TomekMentel

2019-09-30 09:41 UTC, metho requested changes

2019-09-30 09:41 UTC, metho commented on src/test/java/com/kodilla/ecommercee/domain/ProductTest.java
> +        Assert.assertNotEquals(0, saveProduct1);
Ta assercja wygląda podejrzanie. Porównujesz saveProduct który jest typu Optional z wartością 0. To zawsze będzie różne od siebie

2019-09-30 09:41 UTC, metho commented on src/test/java/com/kodilla/ecommercee/domain/ProductTest.java
> +        Assert.assertNotEquals(0, saveProduct1);
Ta assercja wygląda podejrzanie. Porównujesz saveProduct który jest typu Optional z wartością 0. To zawsze będzie różne od siebie

2019-09-30 09:41 UTC, metho commented on src/test/java/com/kodilla/ecommercee/domain/ProductTest.java
> +        Assert.assertTrue(saveProduct.isPresent());
Tutaj ok

2019-09-30 09:41 UTC, metho commented on src/test/java/com/kodilla/ecommercee/domain/ProductTest.java
> +        Assert.assertNotEquals(0, saveProduct1);
Ta assercja wygląda podejrzanie. Porównujesz saveProduct który jest typu Optional z wartością 0. To zawsze będzie różne od siebie

2019-09-30 09:41 UTC, metho commented on src/test/java/com/kodilla/ecommercee/domain/ProductTest.java
> +package com.kodilla.ecommercee.domain;
Może warto by było w teście sprawdzić nie tylko zapisanie produktu, ale powiązanego z nim Carta skoro używasz go w teście

2019-09-30 20:18 UTC, TomekMentel commented
zmiana porównania Optional z wartością 0, na is.Present.
Dopisałem sprawdzenie poprawności ilości produktów w Koszyku.

2019-10-01 18:36 UTC, mps4dev requested changes
:-1:

2019-10-01 18:36 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
>          System.out.println("Get user by ID");
Nie używamy `System.out.println`

2019-10-01 18:36 UTC, mps4dev commented on src/test/java/com/kodilla/ecommercee/domain/ProductTest.java
> +        Assert.assertTrue(saveProduct.isPresent());
proponuję używać w takich przypadkach biblioteki assertJ i można to zapisać wowczas:
`assertThat(savedProduct).isPresent();`

2019-10-01 18:36 UTC, mps4dev commented on src/test/java/com/kodilla/ecommercee/domain/ProductTest.java
> +        Optional<Product> saveProduct = productRepository.findById(productId);
literowka: `savedProduct`

2019-10-01 18:36 UTC, mps4dev commented on src/test/java/com/kodilla/ecommercee/domain/ProductTest.java
> +        Optional<Product> saveProduct3 = productRepository.findById(product3Id);
`saved`

2019-10-01 19:26 UTC, TomekMentel commented
Cofnąłem się o dwa commity ponieważ wrzuciłem UserController przez przypadek,który już był poprawiony przeż inną osobe.

2019-10-04 15:19 UTC, metho approved these changes

2019-10-06 19:11 UTC, mps4dev requested changes
:-1:

2019-10-06 19:11 UTC, mps4dev commented on src/test/java/com/kodilla/ecommercee/domain/ProductTest.java
> +        productRepository.deleteById(product1Id);
jak jest @Transactional, to czy jest konieczność ręcznego cleanUpu?

2019-10-10 08:35 UTC, mps4dev reviewed
wygląda okej, drobne uwagi tylko

2019-10-10 08:35 UTC, mps4dev commented on src/test/java/com/kodilla/ecommercee/domain/ProductTest.java
> +    ProductGroupRepository productGroupRepository;
linebreak

2019-10-10 08:35 UTC, mps4dev commented on src/test/java/com/kodilla/ecommercee/domain/ProductTest.java
> +    @Transactional
skoro masz @Transactional na kazdej metodzie, to daj adnotacje na klasie

2019-10-12 20:07 UTC, ghost approved these changes

2019-10-13 10:41 UTC, merged