JDP190903-23: CartController - rzeczywista implementacja metod
metho/project-JDP-1909-03 pull request #39
Opened 2019-10-06 11:26 UTC by mwiski

2019-10-06 19:10 UTC, mps4dev requested changes
:-1:

2019-10-06 19:10 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public List<ProductDto> getCartProducts(@RequestParam Long cartId) throws CartNotFoundException {
zastanowiłbym się na @PathParam

2019-10-06 19:10 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    public void addCart(final Cart cart) {
czy te metody nam są potrzebne? Przy dobrze zrobionych mapowaniach obustronnych dodanie produktu do kolejnego koszyka pociąga za sobą fakt, że wśrod koszyków, w ktorych znajdue się produkt, będzie ten koszyk

2019-10-06 19:10 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/dto/CartDto.java
> +@Setter
`@Data`

2019-10-06 19:10 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/mapper/CartMapper.java
> +    public CartDto mapToCartDto(final Cart cart) {
wystarczy w nazwie `toCartDto`

2019-10-06 19:10 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/mapper/UserOrderMapper.java
> +    public UserOrderDto mapToUserOrderDto(final UserOrder userOrder) {
`toUserOrderDto`

2019-10-06 19:10 UTC, mps4dev commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +        User user = userRepository.findById(userId).orElseThrow(UserNotFoundException::new);
Lepiej w repozytorium dac metode `findOrThrow`
`default User findOrThrow(Long id) { findOneById(id).orElseThrow(UserNotFoundException::new); }`
A jeszcze lepiej wprowadzić `AbstractRepository` i zgeneralizować:
`default T findOrThrow(Long id) { findOneById(id).orElseThrow(EntityNotFoundException::new); }` :)

2019-10-07 16:10 UTC, mwiski commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +        User user = userRepository.findById(userId).orElseThrow(UserNotFoundException::new);
Zamienić wszystkie Exceptions encji np. UserNotFoundException, ProductNotFoundException na jedno EntityNotFoundException?

2019-10-07 19:03 UTC, mwiski commented
@metho @matimarkiewicz Prośba o re-review

2019-10-07 19:22 UTC, matimarkiewicz reviewed
Wygląda ok, tylko skoryguj konflikty. :)

2019-10-08 19:53 UTC, metho approved these changes

2019-10-08 19:53 UTC, metho commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public List<ProductDto> getCartProducts(@RequestParam Long cartId) throws CartNotFoundException {
Masz na myśli pewnie @PathVariable? Ale zgadzam się, że pasuje też

2019-10-09 03:30 UTC, matimarkiewicz approved these changes

2019-10-09 16:51 UTC, merged