User endpoints,package domain with (User,UserDto) class.
metho/project-JDP-1909-03 pull request #4
Opened 2019-09-19 18:43 UTC by TomekMentel

Stworzyłm endpointy w UserControler takze w pakiecie domain dwie puste klasy User oraz UserDto.

2019-09-20 06:12 UTC, metho commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getUserKey")
Nie ma potrzeby w nazwie endpointa zwierania nazwy metody jaką wywołujemy. Prościej będzie zmapować np. tak:
POST /v1/user -> createUser
GET /v1/user/{userKey} -> getUser(String userKey)
GET /v1/user -> getAllUsers
/DELETE /v1/user/{userKey} -> deleteUserById(Long userKey)
PUT /v1/user/update -> updateUser

2019-09-20 06:14 UTC, metho requested changes

2019-09-20 06:14 UTC, metho commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @RequestMapping(method = RequestMethod.POST, value = "createUser")
Nie ma potrzeby w nazwie endpointa zwierania nazwy metody jaką wywołujemy. Prościej będzie zmapować np. tak:
POST /v1/user -> createUser
GET /v1/user/{userKey} -> getUser(String userKey)
GET /v1/user -> getAllUsers
/DELETE /v1/user/{userKey} -> deleteUserById(Long userKey)
PUT /v1/user/update -> updateUser

2019-09-20 16:44 UTC, TomekMentel commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @RequestMapping(method = RequestMethod.POST, value = "createUser")
Poprawiłemem wedug zaleceń metho endpointy w UserControler i zmieniłem Annotations na krótkie.

2019-09-21 09:15 UTC, metho submitted a review, later dismissed

2019-09-22 11:25 UTC, metho approved these changes

2019-09-22 12:25 UTC, merged