JDP190903-16
metho/project-JDP-1909-03 pull request #40
Opened 2019-10-06 16:53 UTC by matimarkiewicz

2019-10-06 18:52 UTC, mwiski requested changes

2019-10-06 18:52 UTC, mwiski commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
>      @GetMapping(value = "/all")
Możesz usunąć "value" i zostawić samo "all"

2019-10-06 18:52 UTC, mwiski commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +        return userOrderService.getUserOrder(orderId);
Nazwy metod serwisowych można zamienić tak, aby brzmiały jak metody kontrolera, czyli tu: getOrder. Podobnie w pozostałych metodach

2019-10-06 18:52 UTC, mwiski commented on src/main/java/com/kodilla/ecommercee/service/UserOrderService.java
> +        return userOrderMapper.mapToUserOrderDtoList(userOrders);
Można uprościć: return userOrderMapper.mapToUserOrderDtoList(userOrderRepository.findAll());

2019-10-06 18:52 UTC, mwiski commented on src/test/java/com/kodilla/ecommercee/domain/UserOrderTestSuite.java
> +    User user = new User(null, "Jan", "Kowalski");
Można dodać private. A zamiast null w konstruktorze, to dodać konstruktor bez id w klasie User

2019-10-06 18:52 UTC, mwiski commented on src/test/java/com/kodilla/ecommercee/domain/UserOrderTestSuite.java
> +        Assert.assertTrue( userOrderRepository.findAll().size() == 0);
Możesz usunąć spację po otwartym nawiasie. Może zmienić asercję na findAll.isEmpty()?

2019-10-07 14:52 UTC, mwiski approved these changes

2019-10-07 18:55 UTC, metho approved these changes

2019-10-07 18:56 UTC, merged